version: '3'

services:

  mysql:
    image: mysql:latest
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3309:3306

volumes:
  mysqldata: